---
packages:
- name: receptor
  version: !binary |-
    YTliOWM0Y2ZhZGJlMzMxOTIzZDQ1OTJhOGNmNzUxM2Y1MWJmMjNhOQ==
  sha1: !binary |-
    ODIzNDgxNmM0ZDM4YmY1MGM0ZDQwODc5MzNjOGVkNmViNDllODE2Zg==
  fingerprint: !binary |-
    YTliOWM0Y2ZhZGJlMzMxOTIzZDQ1OTJhOGNmNzUxM2Y1MWJmMjNhOQ==
  dependencies:
  - golang_1.4
- name: executor
  version: !binary |-
    ZTRkNGY0NzI3NTk1ZTFjMzRjYzhjZTc4MDQ1MjIzZjAxOGE1OTEyMg==
  sha1: !binary |-
    N2ZhOGJiZDc3NGFkYmU0N2IzZDlhY2RiMDM2MTFlNDM0YWJmMTZhNA==
  fingerprint: !binary |-
    ZTRkNGY0NzI3NTk1ZTFjMzRjYzhjZTc4MDQ1MjIzZjAxOGE1OTEyMg==
  dependencies:
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  sha1: !binary |-
    ZjA5NTMzNGE4N2Q2NmRmOTc0YjA5YzcwMjFlYWQ1MTkxM2E4NjMwNQ==
  fingerprint: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  dependencies: []
- name: cf-cli
  version: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  sha1: !binary |-
    MGZiYjZlNmY0Nzg4ZGFhMjZhZjg1YTQxYjE0NjkzMmIzODFiOTM1OA==
  fingerprint: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  dependencies: []
- name: rep
  version: !binary |-
    Y2RiOWUxMmNiODI2NTcyODQxZDQwMTEyY2Y4NTNmNGYzMzA2MjE5NA==
  sha1: !binary |-
    YTMzODdkYmZlYWU5NDM3MWFjMjdmMzI0NWRhZDVhMzE3ZmI2YjMxMw==
  fingerprint: !binary |-
    Y2RiOWUxMmNiODI2NTcyODQxZDQwMTEyY2Y4NTNmNGYzMzA2MjE5NA==
  dependencies:
  - golang_1.4
- name: tps
  version: !binary |-
    MGExMzAyYTc2MWQyNTM0YzM0MzE3YTJhYmEzNjFmZDFmY2Y3NGM4NQ==
  sha1: !binary |-
    Yzg0ODQwYjk1ZDcyZWU3YTljNGJiNDk1OWIyZDNkYmUwMGYzNzc5Zg==
  fingerprint: !binary |-
    MGExMzAyYTc2MWQyNTM0YzM0MzE3YTJhYmEzNjFmZDFmY2Y3NGM4NQ==
  dependencies:
  - golang_1.4
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  sha1: !binary |-
    YWFkOTg4OTliMzNjM2RlNWY2Y2ZkNTNiMThmZGIwODMxMDcwNTlhYQ==
  fingerprint: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  dependencies:
  - golang_1.4
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: acceptance-tests
  version: !binary |-
    MmExNmRiYTVlOWIxNTFkZGM5MDQ1OTU3YTNhMWY4MjAxZDdmZjQ1OQ==
  sha1: !binary |-
    YjA1MDgwYmYwZGVjZjAwZmMyZGRlZjg2YWVhOTkzODNlYWI3NDk0Mg==
  fingerprint: !binary |-
    MmExNmRiYTVlOWIxNTFkZGM5MDQ1OTU3YTNhMWY4MjAxZDdmZjQ1OQ==
  dependencies:
  - golang_1.4
- name: linux-circus
  version: !binary |-
    OTFiMGIzZmExMTU3N2FiMTQ1ZmUwNGFkN2RhNjdiZGM0NGQ5NmNlMg==
  sha1: !binary |-
    Y2ZhZWM0YjkxNDdiOGQ0NGYzMGRjNjU4YTJlNzQ4YjM0OTYzNGRjMA==
  fingerprint: !binary |-
    OTFiMGIzZmExMTU3N2FiMTQ1ZmUwNGFkN2RhNjdiZGM0NGQ5NmNlMg==
  dependencies:
  - golang_1.4
- name: auctioneer
  version: !binary |-
    NWIyNDc2ODIwMmNkMDVlMGM4ZDA5ODgwZGE3ZjdkN2M0YWNiN2U2Zg==
  sha1: !binary |-
    YTYzMDI3NzkyNWM5MmRiZmJlZjZmZDNkNTYwZDA5NTgyYzExZDU1ZA==
  fingerprint: !binary |-
    NWIyNDc2ODIwMmNkMDVlMGM4ZDA5ODgwZGE3ZjdkN2M0YWNiN2U2Zg==
  dependencies:
  - golang_1.4
- name: nsync
  version: !binary |-
    YTlmOTJjYzkwZDNiYmU4NWM1MTE5NWE5NzQyM2E3MzFiN2EyNjM2YQ==
  sha1: !binary |-
    NjU1MDdkYzMxY2U3Njc1NTE1ZTBlODU5ZGFkMjRlNmI5M2QwMGI5Mw==
  fingerprint: !binary |-
    YTlmOTJjYzkwZDNiYmU4NWM1MTE5NWE5NzQyM2E3MzFiN2EyNjM2YQ==
  dependencies:
  - golang_1.4
- name: etcd_metrics_server
  version: !binary |-
    ZmYyMDUzZDM0YmUxZWUwMTA4MTQ3YzZiYTc5MDdjM2MzMTZkYzEzZQ==
  sha1: !binary |-
    NTcyM2Q3ZmZlZmRhYmVlZWUzYTRiNmQwYjIwMDA0NTA1OTVkOGJlMw==
  fingerprint: !binary |-
    ZmYyMDUzZDM0YmUxZWUwMTA4MTQ3YzZiYTc5MDdjM2MzMTZkYzEzZQ==
  dependencies:
  - golang_1.4
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: runtime_metrics_server
  version: !binary |-
    Y2FlODYyNDk4N2UxZTE1NjdlY2U3ODJjMDg2MzNhOTVlYjllYWU4OQ==
  sha1: !binary |-
    MDA5ODc2MWU2ZDRkMmI2M2JhZTZmYzlkNjRiMzkxZjIyYjU4YzI2ZQ==
  fingerprint: !binary |-
    Y2FlODYyNDk4N2UxZTE1NjdlY2U3ODJjMDg2MzNhOTVlYjllYWU4OQ==
  dependencies:
  - golang_1.4
- name: garden-linux
  version: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  sha1: !binary |-
    NmU1ZWEyYmYwZGU0ZGY1YjIzZTQzNTUxYjNkYmI5ODUxZWNlYWU0OQ==
  fingerprint: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  dependencies:
  - golang_1.4
- name: converger
  version: !binary |-
    NGM0ODc3ODNkYzk0OGFjYzcwMGRjMDdlYjFiMDU1YzVmNGJiMTliMw==
  sha1: !binary |-
    ODA0NDllOGMxNTE5YWUwNDA5OTFkY2MxODg1NTQzMmQyMTY5NjM2MQ==
  fingerprint: !binary |-
    NGM0ODc3ODNkYzk0OGFjYzcwMGRjMDdlYjFiMDU1YzVmNGJiMTliMw==
  dependencies:
  - golang_1.4
- name: docker-circus
  version: !binary |-
    NTk2MTMwOWVkNjgyNDk0NWIxODkyZDdlNDk1NzZmZTUzODNiNjBlNw==
  sha1: !binary |-
    NTIwMmYzNzMxOGIxZWVhZjgzMjMyMDhiMTI4ZmY3ZGM3OWQ5NDBkMQ==
  fingerprint: !binary |-
    NTk2MTMwOWVkNjgyNDk0NWIxODkyZDdlNDk1NzZmZTUzODNiNjBlNw==
  dependencies:
  - golang_1.4
- name: file_server
  version: !binary |-
    MDQ5YmRhYWU5ZTYzMjBkMTQzZmU4MGM2ZTIyYzJmODhkYTgyYjRiYw==
  sha1: !binary |-
    MjZhZjNjNGQ2Y2QyZWZiYWViODA5Mzg4M2U2YTA0MDg1YjM4MmQ4NQ==
  fingerprint: !binary |-
    MDQ5YmRhYWU5ZTYzMjBkMTQzZmU4MGM2ZTIyYzJmODhkYTgyYjRiYw==
  dependencies:
  - golang_1.4
- name: etcd
  version: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  sha1: !binary |-
    ZTMzMWE3Y2QwZjM5NjRjZmJhOTQxZGU2MTMwMzdmYjQyZGY4YzljYg==
  fingerprint: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  dependencies:
  - golang_1.4
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: stager
  version: !binary |-
    NTM0NjUwOTA2ZTkxMjVjMzEyZGRiYWIxNjE0OGFjYjg4OTE4MGFhNQ==
  sha1: !binary |-
    NTQ2MWRjMjgwNmQ3NjM5N2QwZGQ2MjYwMTU5MzQxYmVhMjRjMDA4YQ==
  fingerprint: !binary |-
    NTM0NjUwOTA2ZTkxMjVjMzEyZGRiYWIxNjE0OGFjYjg4OTE4MGFhNQ==
  dependencies:
  - golang_1.4
- name: route_emitter
  version: !binary |-
    ZGMzMDBjMDA2NzI2N2NlZjY5ZjI2NGQ4NTQ0MGIwMTk1MzFmMmQ5YQ==
  sha1: !binary |-
    NTkxNjEwZGE5MTI2NzgxM2MwYmJlYjg0NmQ4MzRkY2VjMDI1YTlhZg==
  fingerprint: !binary |-
    ZGMzMDBjMDA2NzI2N2NlZjY5ZjI2NGQ4NTQ0MGIwMTk1MzFmMmQ5YQ==
  dependencies:
  - golang_1.4
jobs:
- name: receptor
  version: !binary |-
    YjgxMzY5ZDA5MmIzN2I4MDBjN2Y2YzMyOWNmODI0ZjFlMTM2YzQ1Yw==
  fingerprint: !binary |-
    YjgxMzY5ZDA5MmIzN2I4MDBjN2Y2YzMyOWNmODI0ZjFlMTM2YzQ1Yw==
  sha1: !binary |-
    OGQwNTU3YzBhZDlmM2FmY2IxODRhOTk3MWRlODAwNTZjOTA5N2NhZg==
- name: executor
  version: !binary |-
    MDUxYjNiZTNlMTNjZjY5MmJjZmNjYWM0ODVlMWE1MTM3MGI3YzIzMg==
  fingerprint: !binary |-
    MDUxYjNiZTNlMTNjZjY5MmJjZmNjYWM0ODVlMWE1MTM3MGI3YzIzMg==
  sha1: !binary |-
    ZTEyNDI2YTZiNGU5ZjQwNTVlMWJiNjM3OTgzN2VhZjQ2NzYxYmY0ZQ==
- name: rep
  version: !binary |-
    ZDRkOGQ0ZTY0MWM2MTM2ZjJlMDViNGFlMjM0OTMyYmU4YWU3OTFiZA==
  fingerprint: !binary |-
    ZDRkOGQ0ZTY0MWM2MTM2ZjJlMDViNGFlMjM0OTMyYmU4YWU3OTFiZA==
  sha1: !binary |-
    ODhiZjFlYThkYmQxN2I5NmQxNGY0OWIxYjJmMjcwYTliOGFhY2Q5NQ==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: auctioneer
  version: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  fingerprint: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  sha1: !binary |-
    NmJjNTdmZWZjZDI5NjliY2M0NmRmNDIzYWJhNWM4OTliOWFmNGIwYg==
- name: nsync
  version: !binary |-
    OGI3MzY5NWJkYzAxMjk2MzAyMzE3YTdjZjVmNGU5N2M1MWI3MjZlZQ==
  fingerprint: !binary |-
    OGI3MzY5NWJkYzAxMjk2MzAyMzE3YTdjZjVmNGU5N2M1MWI3MjZlZQ==
  sha1: !binary |-
    ZTVmNWFiZDQ2ZTU5NGQyNzIzMTM0NDA1NzU4NDI3NDA0NjU3NzA0Ng==
- name: etcd_metrics_server
  version: !binary |-
    NzczNGE5YzllMjZjNTkwMTQyNDZjOWZiYjg3MGQyNTRmNzQwODQwZA==
  fingerprint: !binary |-
    NzczNGE5YzllMjZjNTkwMTQyNDZjOWZiYjg3MGQyNTRmNzQwODQwZA==
  sha1: !binary |-
    NWEzYjkyZjVkMmU5Nzg5YTNmNjY0ZWM4NjZkNDViNmE2ZDdhZTA4Mg==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: converger
  version: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  fingerprint: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  sha1: !binary |-
    YzgwNzAwYThkYWU0MTM0MTk4YTUyOTgyODkyZTNlMDMzMGI3OGNjNw==
- name: file_server
  version: !binary |-
    NDllYTc4NTVhZDQxYjE4NmUxNWFhMGQ0NzY0YWY2MzcyOThlZjRjMQ==
  fingerprint: !binary |-
    NDllYTc4NTVhZDQxYjE4NmUxNWFhMGQ0NzY0YWY2MzcyOThlZjRjMQ==
  sha1: !binary |-
    ODQxMTNkZjAwNjBjNDRmYWZmYjUzZWQ3YTEyZTMxYWNmNzNmMTMwOQ==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: route_emitter
  version: !binary |-
    OTI3ZjQ5YTczODhkYTA4ODc2YzA2MTI2MTYwZWNjNjcxYWRjZDU1Yw==
  fingerprint: !binary |-
    OTI3ZjQ5YTczODhkYTA4ODc2YzA2MTI2MTYwZWNjNjcxYWRjZDU1Yw==
  sha1: !binary |-
    Y2QxYmQ2MjlhMWE4OTlmMTBhYWE5NTA1MjE5NGE5NTlhZWZkODJmMQ==
commit_hash: 4505dc45
uncommitted_changes: true
name: diego
version: '0.742'
