---
packages:
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    NWIwZmZiYTAxMGIyM2RkMjFlZjIxZTdjMDM4NWQ0NjhhNWRhYTNiMw==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  dependencies: []
- name: linux-circus
  version: !binary |-
    ZjA0MzJkZDFkNTg3ODhjMTdmYjc2NDJlNTYzN2Q5ZWJkZTgzMWJmNA==
  sha1: !binary |-
    MDk0YWRmMjViYThlMDUxOWU4NGMyNzNmOTI5ZTA4N2IzY2ZhYjIyMw==
  fingerprint: !binary |-
    ZjA0MzJkZDFkNTg3ODhjMTdmYjc2NDJlNTYzN2Q5ZWJkZTgzMWJmNA==
  dependencies:
  - golang_1.4
- name: receptor
  version: !binary |-
    NTAxOWFiZDIwNzc2NmJlM2MxZGU5NjJjOWJiZGQ1MGI0NWIwMzRlMw==
  sha1: !binary |-
    MmE0OTRkYzY4MTE2MmU1MjI5NmM0N2ZkNzk3NjA1NzQzNTQ1YjQ0ZA==
  fingerprint: !binary |-
    NTAxOWFiZDIwNzc2NmJlM2MxZGU5NjJjOWJiZGQ1MGI0NWIwMzRlMw==
  dependencies:
  - golang_1.4
- name: etcd_metrics_server
  version: !binary |-
    NjYwYzEwNDk4MGYyMTk1NjI2NzQyYmVmMTg0ZTgwYmYzZGJkNTQ1ZQ==
  sha1: !binary |-
    MjNhN2IyNWM1OTI1ZjQ0NzgwNTgxMjU2MDVkNzAyZTIzOWM4ODdjMA==
  fingerprint: !binary |-
    NjYwYzEwNDk4MGYyMTk1NjI2NzQyYmVmMTg0ZTgwYmYzZGJkNTQ1ZQ==
  dependencies:
  - golang_1.4
- name: docker-circus
  version: !binary |-
    YjgwYmYxZmZjZWQwOTY0ODY4YmE0Y2ExZjZmZGNlYTcwMDM0MGE1Nw==
  sha1: !binary |-
    Zjk5NTdjNWFiMGQ1MDk3NTAwMDA2MDc5MWY2YTI3ZmQwOGUzZTNhZg==
  fingerprint: !binary |-
    YjgwYmYxZmZjZWQwOTY0ODY4YmE0Y2ExZjZmZGNlYTcwMDM0MGE1Nw==
  dependencies:
  - golang_1.4
- name: garden-linux
  version: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  sha1: !binary |-
    NmU1ZWEyYmYwZGU0ZGY1YjIzZTQzNTUxYjNkYmI5ODUxZWNlYWU0OQ==
  fingerprint: !binary |-
    OGNkYWFjMGZlODk3ZDk3OTVjZDRmN2E5ZjMzY2I4OGZjY2M2MjI5ZQ==
  dependencies:
  - golang_1.4
- name: cf-cli
  version: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  sha1: !binary |-
    MGZiYjZlNmY0Nzg4ZGFhMjZhZjg1YTQxYjE0NjkzMmIzODFiOTM1OA==
  fingerprint: !binary |-
    ZmZlYmIwMmUzMTcyMjc4MDc5NTI3MjY1MmNhYTY4ZDNjNGJkZDQ5NA==
  dependencies: []
- name: consul_0.4
  version: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  sha1: !binary |-
    YTlmN2IzZmI2MDZmOWQxMjQ5ZTkwODYxZGUyNGQzYjdjMzFkYjM2Mw==
  fingerprint: !binary |-
    MzAyNzgxNTk5NjIyM2I1NjBiOTdkNDUwMzA2MzZlZjc0NGIyMWJkYw==
  dependencies: []
- name: converger
  version: !binary |-
    MzQyYzI3ZDlhYmI0ZDJmOWE1ZDk4OTkxODJmN2RkZGNhODhmNmRiOQ==
  sha1: !binary |-
    ZDM5MGJkY2Q2NTA5YzU0M2ExMjNmZWNhYWVlOTY1NzNjYTBlYTBiMg==
  fingerprint: !binary |-
    MzQyYzI3ZDlhYmI0ZDJmOWE1ZDk4OTkxODJmN2RkZGNhODhmNmRiOQ==
  dependencies:
  - golang_1.4
- name: etcd
  version: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  sha1: !binary |-
    ZTMzMWE3Y2QwZjM5NjRjZmJhOTQxZGU2MTMwMzdmYjQyZGY4YzljYg==
  fingerprint: !binary |-
    YjNiZWZhOTNjZWJmNGI1NWRkYjVjNjA5Njk1YjM0ZGI4ZTYzMDQ5NQ==
  dependencies:
  - golang_1.4
- name: acceptance-tests
  version: !binary |-
    ZWNjMWRlZDM1ZGVhNTc3ODgzZDIwMjQwMWQ2MDE5MTlmNjkxYjA3Yw==
  sha1: !binary |-
    YmZlNTgwZjU0NDhmZTlhYmVlMWFiYTVkNjM2MDIxZGZhYTc2OWQ5OQ==
  fingerprint: !binary |-
    ZWNjMWRlZDM1ZGVhNTc3ODgzZDIwMjQwMWQ2MDE5MTlmNjkxYjA3Yw==
  dependencies:
  - golang_1.4
- name: golang
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    MGFhZmI4ZDU0M2M3YTExNDdhYzdkMGFhNmMzMzg1NDQyNjRiNjM1MQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  dependencies: []
- name: stager
  version: !binary |-
    ODExZWZmMDRlNDc1ZWM4ZDhhM2ZhNjdlNDZmNGNiMWVmNmIxOWIwZA==
  sha1: !binary |-
    YjYxODMzZjg2ZmY5Y2EyNmEzYjUyODQyZmViMjMxNGZhYTRiZTc2OA==
  fingerprint: !binary |-
    ODExZWZmMDRlNDc1ZWM4ZDhhM2ZhNjdlNDZmNGNiMWVmNmIxOWIwZA==
  dependencies:
  - golang_1.4
- name: executor
  version: !binary |-
    N2YyZTYxZWFkZTg3OTQzZTY5MTAwZTI3MjIxZWMzNTFiNzRmNTQxZg==
  sha1: !binary |-
    Yjc4NDE0ZjI4MDM5YTQ4YTBmYTA2YjhiZGU2NzUwMTQwYzdmMWEzYw==
  fingerprint: !binary |-
    N2YyZTYxZWFkZTg3OTQzZTY5MTAwZTI3MjIxZWMzNTFiNzRmNTQxZg==
  dependencies:
  - golang_1.4
- name: runtime_metrics_server
  version: !binary |-
    OGJhMGQ5MDM1M2E3NDdiMDVlNGY4ZWQzY2YxOTgyZWFjMzJmNzE5Ng==
  sha1: !binary |-
    MDA1ZWVhNWJiNTU3YTViNjVmYmIxNjFkNWVjZmRlMDJkNDdmYjQ2Nw==
  fingerprint: !binary |-
    OGJhMGQ5MDM1M2E3NDdiMDVlNGY4ZWQzY2YxOTgyZWFjMzJmNzE5Ng==
  dependencies:
  - golang_1.4
- name: route_emitter
  version: !binary |-
    OTAzMWVkY2U4Y2ZiYjljODQyOTEwYjU1NGJiMzAxMjE3N2E2NGY3Zg==
  sha1: !binary |-
    ZWViNjY1ZjU5NWJlNDM1ZmU2NjEzNDI1NGRkMzc5MDgzMmRmNGZlNw==
  fingerprint: !binary |-
    OTAzMWVkY2U4Y2ZiYjljODQyOTEwYjU1NGJiMzAxMjE3N2E2NGY3Zg==
  dependencies:
  - golang_1.4
- name: rep
  version: !binary |-
    OGZjNDQ5M2EwNmVkNGQ3NGIzYmM1MzkzNTg4OGZlYWZmOWRmODRhOA==
  sha1: !binary |-
    OWYwZjkwZDA3ZTUyMGM0MDM0MmI2YWNmY2YxZDVlMGI4YTdhNzdmYQ==
  fingerprint: !binary |-
    OGZjNDQ5M2EwNmVkNGQ3NGIzYmM1MzkzNTg4OGZlYWZmOWRmODRhOA==
  dependencies:
  - golang_1.4
- name: nsync
  version: !binary |-
    YzE5ZjI3NDNkY2U0YWYxYWM5MzI3YjEzYWNhNDhjZjdlMzQ4ZTE5Yg==
  sha1: !binary |-
    NmU4YWRhZmIxODRiYTlkMjcwZTY5NTliYjliOTZmZGM3NTNiYzIxYQ==
  fingerprint: !binary |-
    YzE5ZjI3NDNkY2U0YWYxYWM5MzI3YjEzYWNhNDhjZjdlMzQ4ZTE5Yg==
  dependencies:
  - golang_1.4
- name: auctioneer
  version: !binary |-
    ODRhNDYxZThhN2FlMDEyYTVlZjk5ODI3OWIwZGRiNjZhYTJiZjg3Nw==
  sha1: !binary |-
    ZWEzOWUwNTgxNGU3OWEyM2I2YjY4ZWE0NzlhYTA4MjhiZDUxY2U0Mw==
  fingerprint: !binary |-
    ODRhNDYxZThhN2FlMDEyYTVlZjk5ODI3OWIwZGRiNjZhYTJiZjg3Nw==
  dependencies:
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  sha1: !binary |-
    ZjA5NTMzNGE4N2Q2NmRmOTc0YjA5YzcwMjFlYWQ1MTkxM2E4NjMwNQ==
  fingerprint: !binary |-
    ODBmZDEwYWFjYTdmYWZhZGE2ZTdmMjI4ZjAzYzUwMjRmYWEwYjUxYQ==
  dependencies: []
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    MTUxMjA2NjY3ZmI0MjQzMTUzYjUwODA2ZTk3YjFmYjdkZTlhOTRjZg==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  dependencies: []
- name: smoke-tests
  version: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  sha1: !binary |-
    YWFkOTg4OTliMzNjM2RlNWY2Y2ZkNTNiMThmZGIwODMxMDcwNTlhYQ==
  fingerprint: !binary |-
    YjM0MGM1NDFmMWI1Y2ZiZGEzODVjNzkzNzhkMTYxNTE4ZDI5MjUxMw==
  dependencies:
  - golang_1.4
- name: pid_utils
  version: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  sha1: !binary |-
    ODNlZmQ2ZGE2OGYzMTFhZGFiYzg0OTMxOGU1NjcxMjczODU3YTdjZg==
  fingerprint: !binary |-
    MmIwMGU0NjJlMzdhYjkzNTJmZTAxNmQ4NjYzOTVmNzM0MzA2OTg4MA==
  dependencies: []
- name: tps
  version: !binary |-
    ZDQ4ZDQwZTk0NDdkYTg5NzJhOWRkNzAxMmZkODlkZGJjZDA1ZjRjMQ==
  sha1: !binary |-
    YmI0NzMyMzRhYzdlZTdlNGM5ZmVmMGZlYmRlMjUwYWI4Y2Y1MmJmOQ==
  fingerprint: !binary |-
    ZDQ4ZDQwZTk0NDdkYTg5NzJhOWRkNzAxMmZkODlkZGJjZDA1ZjRjMQ==
  dependencies:
  - golang_1.4
- name: file_server
  version: !binary |-
    ZGJmZjc2YTNmMWJhY2FkMDI1MTUxYzJhYTQ0NmJiOTBhZWM0MjI3YQ==
  sha1: !binary |-
    MzI2NWFjYjc2MjFiMTJkZjNkNGU5MmNiNTlkYjg4MGNmOGM0MzFkMg==
  fingerprint: !binary |-
    ZGJmZjc2YTNmMWJhY2FkMDI1MTUxYzJhYTQ0NmJiOTBhZWM0MjI3YQ==
  dependencies:
  - golang_1.4
- name: rootfs_lucid64
  version: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  sha1: !binary |-
    NGUyOTNiNWQwMjBkNmRiZGVhN2FmMjZhYmUzZTRmMDg2NGJjNjFmMg==
  fingerprint: !binary |-
    MGM3NDIwZjdmNjJlYzQzZTU0MGE0NjU2YzE1YTE1NTZkYjRkN2Y3Zg==
  dependencies: []
jobs:
- name: receptor
  version: !binary |-
    YjgxMzY5ZDA5MmIzN2I4MDBjN2Y2YzMyOWNmODI0ZjFlMTM2YzQ1Yw==
  fingerprint: !binary |-
    YjgxMzY5ZDA5MmIzN2I4MDBjN2Y2YzMyOWNmODI0ZjFlMTM2YzQ1Yw==
  sha1: !binary |-
    OGQwNTU3YzBhZDlmM2FmY2IxODRhOTk3MWRlODAwNTZjOTA5N2NhZg==
- name: etcd_metrics_server
  version: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  fingerprint: !binary |-
    Zjc5ZTk4NDRmZjA2MzM5MmEyZWU3NTBjMTc2ZGE4ZTgyMTI5YmFiYQ==
  sha1: !binary |-
    ZGFkMWZmZTQ4MWY4MjJmYjc4ZmQzYWM3YTRjZjVhNDAyZjE0OTIwOQ==
- name: garden-linux
  version: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  fingerprint: !binary |-
    MjQwMjZiNzE1YTI2MDE1MzFhYjg2NDNiMTllYzNiYTZmNmQ3ZmFkZA==
  sha1: !binary |-
    NTdlOWJmZTM5ODVhZWI5MzY5Mjc0MGNhZTg4ZTM5YzM1YWI3YTIwMg==
- name: converger
  version: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  fingerprint: !binary |-
    MDk3ZGU5NThkOTA2MDIwYjZlOTYxMDI5NWNmNzc0YTFiYmFmYjA1MQ==
  sha1: !binary |-
    YzgwNzAwYThkYWU0MTM0MTk4YTUyOTgyODkyZTNlMDMzMGI3OGNjNw==
- name: etcd
  version: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  fingerprint: !binary |-
    ZjgxNTBlMWY4NDllMjZhZjRiYWQ2YmQ2NzU0OGQ3MDVlYWNjNGYyNA==
  sha1: !binary |-
    MzFiNDJiOTYwYzBkMWUwMDhkZTE4YmFlNDYxZDI5OTBkZjllNGZjZQ==
- name: acceptance-tests
  version: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  fingerprint: !binary |-
    NWQ4MDUzM2RjM2EyMWUwYzE5YTNiNTNiZGRkNjFhMTgzNjU3MDQ1Nw==
  sha1: !binary |-
    OGExNDljMDI3NzNhOTJlNDEyOTlkM2IxNjYxNjk3OGU1ZGU5ODA4MQ==
- name: stager
  version: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  fingerprint: !binary |-
    M2Y5NDRiNGE3YTBjYTdmZDAzMWJkZDkwODg4Mzk0NGI5ZGNiOTRhOQ==
  sha1: !binary |-
    NmQ5NWQwM2MwYjE0MzEzNTQxZjQ3MmMzZjcwMTE1YzMwMzgyYWNiMA==
- name: executor
  version: !binary |-
    MDUxYjNiZTNlMTNjZjY5MmJjZmNjYWM0ODVlMWE1MTM3MGI3YzIzMg==
  fingerprint: !binary |-
    MDUxYjNiZTNlMTNjZjY5MmJjZmNjYWM0ODVlMWE1MTM3MGI3YzIzMg==
  sha1: !binary |-
    ZTEyNDI2YTZiNGU5ZjQwNTVlMWJiNjM3OTgzN2VhZjQ2NzYxYmY0ZQ==
- name: runtime_metrics_server
  version: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  fingerprint: !binary |-
    YmI1NzY3MDIxZWJmMWU0NjM5YjQ3YzllZTgxM2Q1NGQ2ZjljNmJjZQ==
  sha1: !binary |-
    MjFlZDQyOGUwNTEwZDE0YzIwNjg1OGI3YzFjZTFhNTczMDNjOTMyZA==
- name: route_emitter
  version: !binary |-
    OTI3ZjQ5YTczODhkYTA4ODc2YzA2MTI2MTYwZWNjNjcxYWRjZDU1Yw==
  fingerprint: !binary |-
    OTI3ZjQ5YTczODhkYTA4ODc2YzA2MTI2MTYwZWNjNjcxYWRjZDU1Yw==
  sha1: !binary |-
    Y2QxYmQ2MjlhMWE4OTlmMTBhYWE5NTA1MjE5NGE5NTlhZWZkODJmMQ==
- name: rep
  version: !binary |-
    ZDRkOGQ0ZTY0MWM2MTM2ZjJlMDViNGFlMjM0OTMyYmU4YWU3OTFiZA==
  fingerprint: !binary |-
    ZDRkOGQ0ZTY0MWM2MTM2ZjJlMDViNGFlMjM0OTMyYmU4YWU3OTFiZA==
  sha1: !binary |-
    ODhiZjFlYThkYmQxN2I5NmQxNGY0OWIxYjJmMjcwYTliOGFhY2Q5NQ==
- name: nsync
  version: !binary |-
    OGI3MzY5NWJkYzAxMjk2MzAyMzE3YTdjZjVmNGU5N2M1MWI3MjZlZQ==
  fingerprint: !binary |-
    OGI3MzY5NWJkYzAxMjk2MzAyMzE3YTdjZjVmNGU5N2M1MWI3MjZlZQ==
  sha1: !binary |-
    ZTVmNWFiZDQ2ZTU5NGQyNzIzMTM0NDA1NzU4NDI3NDA0NjU3NzA0Ng==
- name: auctioneer
  version: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  fingerprint: !binary |-
    NWU5NzY3ODNjMmE4ZTRhM2QzNjUxNjkyZGE0ZWI0NTVmNTllMDI2Yw==
  sha1: !binary |-
    NmJjNTdmZWZjZDI5NjliY2M0NmRmNDIzYWJhNWM4OTliOWFmNGIwYg==
- name: smoke-tests
  version: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  fingerprint: !binary |-
    ZjA1NzZjNDhkY2U4ZDU4MTRhNDJmOTQ5YWZkMTgzMGQyY2E2NjZhYw==
  sha1: !binary |-
    YjQxNDIyZTJmN2I0NjIyMzA5NTdkOWZlZGI5MDk0MDBlNmEzOTllNg==
- name: consul-agent
  version: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  fingerprint: !binary |-
    Y2M1ODg0YTMxOGFhNmMzYjZiMmY0YmRlNjhkZDI0MmNjNTE0ZTkzZA==
  sha1: !binary |-
    MDExZWM5ZDgyZjcwMzhlYjY3OTdkNDFiMDUyOGQxNGViNTQ4YmIzZg==
- name: tps
  version: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  fingerprint: !binary |-
    ZmIwYmY3Y2U4OThlMDFkMzhiOTZjMThkOWZhYTBjYmYzMWE0N2FkMA==
  sha1: !binary |-
    MjYzMjZiNGFmNGM4NmJhNGEzYWNhOTJhMmYwNGRjMzY3ODM5N2E5Nw==
- name: file_server
  version: !binary |-
    NDllYTc4NTVhZDQxYjE4NmUxNWFhMGQ0NzY0YWY2MzcyOThlZjRjMQ==
  fingerprint: !binary |-
    NDllYTc4NTVhZDQxYjE4NmUxNWFhMGQ0NzY0YWY2MzcyOThlZjRjMQ==
  sha1: !binary |-
    ODQxMTNkZjAwNjBjNDRmYWZmYjUzZWQ3YTEyZTMxYWNmNzNmMTMwOQ==
commit_hash: 42755aa4
uncommitted_changes: true
name: diego
version: '0.727'
